spring:
  datasource:
    url: jdbc:mysql://localhost:3306/base_app
    username: dev
    password: dev 
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true

#Tymeleaf Setting
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates/

#O/RMapper Setting    
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  file: logfile.log
  path: /
  
server: 
  port: 8081 

com:
  freitech:
    model:
      creator:
        folder:
          path: C:\dev\work\spring\workspace\freitech-app\src\main\java\com\freitech\kotetsu
          basePackage: com.freitech.kotetsu

api:
  exchange:
    coincheck:
      key:
        apiKey: JjVINiHVY3Sf6eHO
        secretKey: dftLyjDDBpJfK1iBu_U6XIBwOQNv4x7A
      url:
        base: https://coincheck.com
        transaction: /api/exchange/orders/transactions
        balance: /api/accounts/balance
        trades: /api/trades
    coinExchange:
      version: /v1
      url:
        base: https://www.coinexchange.io/api
        market: /getmarkets
        marketSummaries: /getmarketsummaries
        marketSummary: /getmarketsummary
        orderBook: /getorderbook
        currencies: /getcurrencies
        currency: /getcurrency
        